### ISSUE TITLE
IOError: Unable to open file (Unable to open file: name = '/home/ycw/catkin_ws/src/gpd2/data/ .h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by TONG369** [atenpas/gpd#85]
Hello, excuse me, I have a question that  need to ask you.  When I execute this command: python reshape_hdf5.py pathToTrainingSet.h5 out.h5 size  The terminal outputs the following error:

ycw@mt8500:~/catkin_ws/src/gpd2/pytorch$ python reshape_hdf5.py "/home/ycw/catkin_ws/src/gpd2/data/ .h5" out.h5 100
Traceback (most recent call last):
  File "reshape_hdf5.py", line 24, in <module>
    dset = H5Dataset(sys.argv[1])
  File "reshape_hdf5.py", line 13, in __init__
    h5_file = h5py.File(file_path, 'r')
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2577)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2536)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/h5f.c:1811)
IOError: Unable to open file (Unable to open file: name = '/home/ycw/catkin_ws/src/gpd2/data/ .h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

I downloaded the BigBird  dataset,  which the name of the image is dove_beauty_cream_bar, and the downloaded data type is Raw RGB-D (object_name/rgbd.tgz). I unzip this dataset into my data folder and executed the above command and reported an error. Please have time to help me see it,I am looking  forward to your reply!!!

**Comment by atenpas** [comment]
I do not understand what you're trying to do. Could you explain it? 

The script `reshape_hdf5.py` is meant to be used with a custom HDF5 file, not with the BigBird dataset.

Btw, please use short, concise titles for github issues. Long titles mess up the issues page.
